# Generated by Django 3.2.3 on 2021-06-02 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('hsn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('aptn', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('lrv', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('ssn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('skind', models.CharField(max_length=20)),
                ('sno', models.CharField(max_length=20, null=True)),
                ('hsn', models.ForeignKey(db_column='hsn', null=True, on_delete=django.db.models.deletion.CASCADE, to='smarthome.home')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('rsn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('rname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('pw', models.CharField(default='000000', max_length=20)),
                ('authority', models.BooleanField(default=False)),
                ('hsn', models.ForeignKey(db_column='hsn', null=True, on_delete=django.db.models.deletion.CASCADE, to='smarthome.home')),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('psn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pkind', models.CharField(max_length=20)),
                ('pno', models.IntegerField(null=True)),
                ('pstate', models.BooleanField(default=False)),
                ('ssn', models.ForeignKey(db_column='ssn', null=True, on_delete=django.db.models.deletion.CASCADE, to='smarthome.space')),
            ],
        ),
        migrations.CreateModel(
            name='IOT',
            fields=[
                ('isn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ikind', models.CharField(max_length=20)),
                ('ino', models.IntegerField(null=True)),
                ('istate', models.BooleanField(default=False)),
                ('ssn', models.ForeignKey(db_column='ssn', null=True, on_delete=django.db.models.deletion.CASCADE, to='smarthome.space')),
            ],
        ),
    ]
